config/routes.rb
SampleApp2::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new,:create,:destroy]
  resources :microposts
  resources :replies, only: [:show,:create,:edit,:update,:destroy]
  resources :relationships, only: [:create,:destroy]
  root to:  'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help',to: 'static_pages#help', via: 'get'
  match '/about',to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :micropost
  belongs_to :user
  #default_scope -> {order('created_at ASC')}  #默认就是按时间正序排列
  validates :remark, presence: true, length: {maximum: 5000}
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :signed_in_user, only: [:create,:destroy]
  before_action :correct_user, only: :destroy


  def create
    # @micropost=Micropost.find_by(id: params[:id])  #取不到
    @reply=current_user.replies.build(reply_params)
    # @reply.user_id=current_user.id
    flash[:success]="reply created!"
    respond_to do |format|
      if @reply.save
        #flash[:success]="Micropost created!"
        #format.html {redirect_to root_url,notice: 'Micropost created!' }
        format.html {redirect_to :back }
        format.js
      else
        format.html {render @micropost}
        format.js
      end
    end
  end

  def edit
   @reply=Reply.find_by(id: params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    #@reply = Reply.find_by(id: params[:id])
    @reply = Reply.find_by(id: params[:id])
    flash[:success]="reply was successfully updated!"
    respond_to do |format|
      #if @reply.update_attributes(params[:reply])
      if @reply.update(reply_params)
        format.html { redirect_to :back }
        format.js
      else
        format.html { render @micropost }
        format.js { render @micropost }
      end
    end
  end

  def destroy
    @reply.destroy
    #redirect_to root_url
    respond_to do |format|
      format.html {redirect_to :back }
      format.js
    end
  end

  private
    def reply_params
      params.require(:reply).permit(:remark,:user_id,:micropost_id)
    end 
    def correct_user
      @reply=current_user.replies.find_by(id: params[:id])
      redirected_to :back if @reply.nil?
    end
end

app/views/replies/_reply.html.erb
<div class="reply" id="<%=reply.id%>">
  <div class="pull-left face"  >
    <%= link_to gravatar_for(reply.user), reply.user%>
  </div>
  <div class="infos">
    <div class="info">
      <span class="name"><%= link_to reply.user.name, reply.user %></span>
      <span class="time">Posted <%= time_ago_in_words(reply.created_at) %> ago.</span>
      <span class="opts">
        <%= link_to 'Edit', edit_reply_path(reply), remote:true %>
        <%= link_to "delete", reply, method: :delete,remote:true%>
      </span>
    </div>
    <div class="body">
      <%= wrap(reply.remark) %>
    </div>
  </div>
</div>

app/views/replies/create.js.erb
// 教训：请勿使用‘#’符号进行注释，以免程执行出错
<%if @reply.errors.empty? %>
$("#errors").fadeOut();    //隐藏errors信息，防止提交成功仍有错误信息展示
$('<%= escape_javascript(render  @reply) %>').appendTo('.items').hide().fadeIn();  //更简洁的实现方式
$("#flash").html('<%= escape_javascript(render 'shared/flash_messages') %>').hide().fadeIn(); //flash通知
$('#new_reply')[0].reset();   //重置表单数据
<%else%>
$("#flash").fadeOut();
$("#errors").html('<%= escape_javascript(render 'shared/error_messages', object: @reply) %>').hide().fadeIn();
<%end%>
$('#reply_remark')[0].focus();  //光标栏位重置

app/views/replies/destroy.js.erb
$("#<%=@reply.id%>").fadeOut(function(){$("#<%=@reply.id%>").remove()}); //使用回调函数，确保隐藏动画执行玩后再删除元素

app/views/replies/edit.js.erb
//j 等同于 escape_javascript; .replaceWith 并不等同于 .html ,使用replaceWith更方便;
//区别在于，html()会替换指定元素内部的HTML，而replaceWith()会替换元素本身及其内部的HTML。
$("#flash").fadeOut();
$("#reply > form").replaceWith('<%= j render 'shared/reply_form'  %>');
$('#reply_remark')[0].focus();  //光标栏位重置

app/views/replies/update.js.erb
<%if @reply.errors.empty? %>
  $("#<%= @reply.id %>").replaceWith("<%= j render @reply %>");
  $("#flash").html('<%= escape_javascript(render 'shared/flash_messages') %>').hide().fadeIn();
  <% @reply = Reply.new  %>
  $(".edit_reply").replaceWith('<%= j render 'shared/reply_form'  %>'); //更新表单（1）
  $(".edit_reply")[0].reset(); //重置
<%else%>
  $("#flash").fadeOut();
  $("#errors").html('<%= escape_javascript(render 'shared/error_messages', object: @reply) %>').hide().fadeIn();
<%end%>

app/views/replies/update_copy.js.erb
$("#<%= @reply.id %>").replaceWith("<%= j render @reply %>");
<% @reply = @micropost.replies.build  %>   //reset for new form
$(".edit_reply").replaceWith('<%= j render 'shared/reply_form'  %>');
$(".new_reply")[0].reset();